version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1999:1999" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=<YourStrong@Passw0rd>